### ISSUE TITLE
Spring not working in vagrant with Rails 4.2 since v1.3

### ISSUE THREAD

**Issue by luctus** [rails/spring#390]
Hi, I'm having this error whenever I run "rails console" or whatever other task:

/home/vagrant/.rbenv/versions/2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)

I specified v1.2 now in my Gemfile and it works again.

(Ruby 2.2.0, Rails 4.2)

**Comment by KawaharaTaisuke** [comment]
I'm having same error too.
Just workaround, it works when I modified bin/spring as the following:

```
diff --git a/bin/spring b/bin/spring
index e091824..389f85a 100755
--- a/bin/spring
+++ b/bin/spring
@@ -5,7 +5,7 @@

 unless defined?(Spring)
   require "rubygems"
-  require "bundler"
+  require "bundler/setup"

   if match = Bundler.default_lockfile.read.match(/^GEM$.*?^    (?:  )*spring \((.*?)\)$.*?^$/m)
     Gem.paths = { "GEM_PATH" => Bundler.bundle_path.to_s }
```

But, I'm not sure that it is correct way in view of this comment in bin/spring:

```
# This file loads spring without using Bundler, in order to be fast.
```

If my understanding is correct, "bundler/setup" loads spring with Bundler.

**Comment by KawaharaTaisuke** [comment]
I've read a little more code .
It seems to that the problem occurred after this commit: 64e82e88bc

"rails console" works correctly when I modified bin/spring as the following:

```
diff --git a/bin/spring b/bin/spring
index e091824..cfd7cfc 100755
--- a/bin/spring
+++ b/bin/spring
@@ -8,7 +8,10 @@ unless defined?(Spring)
   require "bundler"

   if match = Bundler.default_lockfile.read.match(/^GEM$.*?^    (?:  )*spring \((.*?)\)$.*?^$/m)
-    Gem.paths = { "GEM_PATH" => Bundler.bundle_path.to_s }
+    ENV["GEM_PATH"] = ([Bundler.bundle_path.to_s] + Gem.path).join(File::PATH_SEPARATOR)
+    ENV["GEM_HOME"] = nil
+    Gem.paths = ENV
+
     gem "spring", match[1]
     require "spring/binstub"
   end
```

Should ENV["GEM_HOME"] be nil?

64e82e88bc works when after server started.
It does not work when server is not running.

```
% ./bin/spring stop
Spring stopped.
% ./bin/spring rails c
/Users/kawahara_taisuke/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
        from /Users/kawahara_taisuke/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/kawahara_taisuke/Documents/program/ruby/todolist/vendor/bundle/ruby/2.2.0/gems/spring-1.3.2/lib/spring/commands.rb:33:in `<module:Spring>'
        from /Users/kawahara_taisuke/Documents/program/ruby/todolist/vendor/bundle/ruby/2.2.0/gems/spring-1.3.2/lib/spring/commands.rb:4:in `<top (required)>'
        from /Users/kawahara_taisuke/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/kawahara_taisuke/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/kawahara_taisuke/Documents/program/ruby/todolist/vendor/bundle/ruby/2.2.0/gems/spring-1.3.2/lib/spring/server.rb:9:in `<top (required)>'
        from /Users/kawahara_taisuke/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /Users/kawahara_taisuke/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /Users/kawahara_taisuke/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
% bundle exec spring rails c
Loading development environment (Rails 4.2.0)
irb(main):001:0> ^D
% ./bin/spring status
Spring is running:

18222 spring server | todolist | started 7 secs ago
18223 spring app    | todolist | started 7 secs ago | development mode
% ./bin/spring rails c
Loading development environment (Rails 4.2.0)
irb(main):001:0> ^D
```

**Comment by KawaharaTaisuke** [comment]
I investigated this problem, and I found that `spring rails c` failed when GEM_PATH environment does not exist and spring stopped after 64e82e8.

success:
```
./bin/spring binstub --all
GEM_PATH="$HOME/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0" ./bin/spring rails c
```

fail:
```
./bin/spring binstub --all
./bin/spring rails c
```

Is this intended change of behavior in v1.3?

**Comment by davidlormor** [comment]
Just want to confirm I'm running into the same issue with 1.3.x - from a fresh shell session when I try to run any spring commands I get the same `cannot load such file -- bundler/setup (LoadError)` error until I `bundle exec spring start`...downgraded to 1.2.x and everything seems to be working fine.

**Comment by jonleighton** [comment]
This looks like a regression. Are you all using rbenv?

**Comment by KawaharaTaisuke** [comment]
Yes, I'm using rbenv.

**Comment by luctus** [comment]
Me toó!

**Comment by jonleighton** [comment]
I've pushed a fix, I hope. Please could you test it? To do so:

* Check out the code
* Run `rake install`
* Does it work now?
* Run `spring binstub` in your project
* Does it work now?

Thanks

**Comment by KawaharaTaisuke** [comment]
It works! Thanks a lot!

**Comment by davidlormor** [comment]
Still having issues here. I'm able to intermittently resolve them, but seems like the issue is coming from rbenv's path hackery and conflicts between bundler/spring binstubs.  Also occasionally getting the require 'bundler/setup' error resolved only to run into issues with 'spring/server'.  Will update when/if I find the source of the issue.

**Comment by davidlormor** [comment]
I should also add it appears to be related to the fact that my BUNDLE_PATH is set to vendor/bundle instead of the Bundler default...if I delete that config and bundle install to the default path it seems to clear the error

**Comment by jonleighton** [comment]
Ok, I'm going to release the existing fix for now. If @davidlormor can follow up with more info then we can hopefully fix the other issue in a future release.

**Comment by davidlormor** [comment]
Everything seems to be working now...seems like I gummed up the works at some point by not running `spring binstubs` under `bundle exec` or something of the like.  After a bit of .zshrc cleanup, reinstalling spring, and rebuilding all my binstubs I seem to be in the clear... :pray: ...thanks for the fix!

**Comment by luctus** [comment]
yes, it works now! Thank you very much @jonleighton

**Comment by metaskills** [comment]
Had to update bundler for it to work for me. Was on 1.9.x and updated to 1.10.3. Thanks y'all.
